[package]
name = "cumulus-consensus"
description = "Proxy Polkadot's consensus as a consensus engine for Substrate"
version = "0.1.0"
authors = ["Parity Technologies"]
edition = "2018"

[dependencies]
# substrate deps
substrate-client = { git = "https://github.com/paritytech/substrate" }
substrate-consensus-common = { git = "https://github.com/paritytech/substrate" }
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }

# polkadot deps
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rh-update-substrate" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rh-update-substrate" }

# other deps
futures = "0.1.21"
tokio = "0.1.8"
parity-codec = "2.0"
log = "0.4"